- symbol: AZGC
  name: 亞馬遜雲創
- symbol: GCR
  name: 嘎核心指標
- symbol: HOLO
  name: Hololive
- symbol: LOVE
  name: 愛馬仕
- symbol: MAID
  name: 女僕特斯
- symbol: MYTHIC
  name: 神話金控
- symbol: NVGX
  name: 輝達圖核
- symbol: SEGA
  name: 世嘉遊戲
- symbol: SOLCR
  name: Solara Crest
- symbol: UNRA
  name: UNION ARENA
- symbol: WAVE
  name: 夏日狂熱
